### ISSUE TITLE
Permission denied on unittests.cfg

### ISSUE THREAD

**Issue by sdanbury** [BrechtDeVlieger/airflow-kube-helm#2]
Hello!

After running the following:

```
$ helm install --name airflow .
```

I get the following error in the webserver init container:
```
$ kubectl logs airflow-web-6df8f8bc46-9rlg5 -c init-airflow
+ bash /usr/local/init-airflow.sh
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/airflow/airflow/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/opt/airflow/airflow/__init__.py", line 36, in <module>
    from airflow import settings, configuration as conf
  File "/opt/airflow/airflow/settings.py", line 30, in <module>
    from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
  File "/opt/airflow/airflow/configuration.py", line 512, in <module>
    with open(TEST_CONFIG_FILE, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/unittests.cfg'
```

I have made a change to the values.yaml to use the `apache/airflow:latest` docker image. I would expect everything to have worked the same, but maybe not.

Versions:
```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sdanbury** [comment]
Used the image this was written for and it worked, silly me opening this. Closing.
